# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  name: MyAgentPool
  demands:
   -  mvn
  
 
steps:

  - task: SonarQubePrepare@7
    inputs:
     SonarQube: 'Sonar1'
     scannerMode: 'other'
     


  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      testResultsFiles: '**surefire-reports/TEST-*.xml'
      javaHomeOption: JDKVersion
      mavenVersionOption: Default
     
     
  
  - task: CopyFiles@2
    inputs:
      Contents: '**/target/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      publishLocation: 'pipeline'
      artifact: 'drop'




    
    


