name: CI - Maven Java

on:
 workflow_dispatch

jobs:
 ci-build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v5.0.0
  - name: Setup Java JDK
    uses: actions/setup-java@v5.0.0
    with:  
     java-version: '17'
     distribution: 'microsoft' 
  - run: mvn --batch-mode --update-snapshots verify
  - run: mkdir staging && cp target/*.jar staging
  - name: Publish the artifact
    uses: actions/upload-artifact@v4.6.2
    with: 
     name:  Package
     path: staging
 test:
  needs: ci-build
  runs-on: ubuntu-latest
  steps:
   - name: Download a Build Artifact
     uses: actions/download-artifact@v5.0.0
     with:
      name: Package
      path: staging
   - name: check download artifact completed
     run: |
        ls
        cd staging
        ls
